spring:
    pulsar:
      administration:
        service-url: pulsar://localhost:6650
      client:
        service-url: pulsar://localhost:6650
      producer:
        batching-enabled: false
        send-timeout-ms: 90000
        producer-name: admintool
        topic-name: persistent://public/default/schema-alerts
logging:
  level:
    org.apache.pulsar: error
    root: error
    ROOT: error
    com.pulsardeveloper: error
    org:
      apache:
        pulsar:
          shade: error
server.port: 8599